### ISSUE TITLE
Turning off channel in the LFP viewer effects naming

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/oephys2nwb#12]
The recording of channel data is not effected by the viewing but it seems the current json parsing is using information from the LFP viewer to decide on the channel names. This somehow results in too many channels being created but not enough names. Maybe the deselected channels are there both empty and with data?

**Comment by KatharineShapcott** [comment]
/cs/projects/ZeroNoise_MONKEY/test_recordings/Cosmos/20221212/BarMapping/001/

**Comment by pantaray** [comment]
Hi! Yes, that seems to be the case. Probably not the best idea to fetch channel names from the viewer...

**Comment by KatharineShapcott** [comment]
Never mind, the bug came from somewhere else!
